name: Test

on:
  push:
    branches: [main]
    paths: ["**.lua"]
  pull_request:
    paths: ["**.lua"]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nvim-versions: ["v0.12.0", "nightly"]
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev

      - name: Install Lua and LuaRocks
        run: |
          pip install hererocks
          hererocks lua51 -r^ --lua=5.1
          echo "$PWD/lua51/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Install luassert
        run: luarocks install luassert
        shell: bash

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Run tests
        run: make test
        env:
          OLLAMA_MODEL_ID: ""
        shell: bash
